version: "3.5"

# networks:
#   default:
#     name: elastic
#     external: false

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data:rw             # Persistence data
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    ports:
      - "5601:5601"
    restart: on-failure
    depends_on:
      - elasticsearch

  logstash:
    build:  
      context: ./logstash/
      dockerfile: Dockerfile
    ports:
      - "5044:5044"
    links:
      - elasticsearch  
    user: root   
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro                # Pipeline configuration
#    command: logstash -f /config-dir/logstash.conf
    restart: on-failure
    depends_on:
      - elasticsearch



  filebeat:
    image: docker.elastic.co/beats/filebeat:7.2.0
    user: root 
    volumes:
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
      - ./filebeat/data:/usr/share/filebeat/data:rw                        # Persistence data
                                                                # Allow access to log files and docker.sock
    restart: on-failure
    # depends_on:
    #   - logstash

  comment-service:
    image: cassiomolin/comment-service:latest
    ports:
      - "8002:8002"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  post-service:
    image: cassiomolin/post-service:latest
    ports:
      - "8001:8001"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"